[package]
name = "shketch"
version = "0.1.0"
authors = ["Seif Kamal <seifskm@gmail.com>"]
edition = "2018"

[dependencies]
terminal = { path = "crates/terminal" }

[workspace]
members = [
    "crates/terminal",
]
