[package]
name = "shketch"
version = "0.1.0"
authors = ["Seif Kamal <seifskm@gmail.com>"]
edition = "2018"

[dependencies]
termion = "~1.5.5"
grid = { path = "grid" }

[workspace]
members = [
    "grid",
]
