name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - if: runner.OS == 'macOS'
      name: Setup Darwin Toolchain
      run: |
        rustup component add clippy-preview
        rustup component add rustfmt-preview
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
    - name: Lint
      run: |
        cargo clippy
        cargo fmt -- --check
